name: angular_color_picker
description: RGB, HSL color pickers for Angular Dart
version: 1.0.0
homepage: https://github.com/tejainece/angular_color_picker
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  lib_colors: ^1.0.5
  ng_bind:

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0

dependency_overrides:
  lib_colors:
    path: ../lib_colors
  ng_bind:
    path: ../ng_bind